version: '3'

services:
  web:
    image: mlops
    build: .
    privileged: true
    network_mode: host
    env_file: .env
    volumes:
      - .:/mlops
      - ./.kaggle:/root/.kaggle
    working_dir: /mlops
    user: root
